# dockerfile 
FROM python:3.11-slim 

# Set workdir inside the container
WORKDIR /app

# Install system dependencies : needed for psycog2, polars, etc..)

RUN apt-get update && apt-get install -y --no-install-recommends \ 
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy dependency file and install python packages

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project
COPY . .

# expose the port the app runs on
EXPOSE 8000

# Default command: run the API with uvicorn 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

